name: Get Sickpicks

on: 
  schedule:
    - cron: '30 6 * * 2,4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Podcasts
      run: |
        npm install
        git clone https://github.com/wesbos/Syntax.git
        node index
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
        
















